layout_spectrum: 0.04301075
color:
  saturation: 0.2326032
  lightness: 0.6971323
  brandStrength: 1
  brandColors:
    - '#FDFDFD'
    - '#10070A'
    - '#AFABA0'
    - '#935314'
    - '#DDD0BD'
  rhythmicContrast: 0.03976858
typography_spectrum: 1
name: Joe of life
