layout_spectrum: 0.768426
typography_spectrum: 0.5167506
color:
  saturation: 0.2326032
  lightness: 0.6971323
  brandStrength: 0.1263381
  rhythmicContrast: 0.03976858
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Joe of life
